# Lab 03 - NumPy Library - Florentin Degbo

- NumPy is an open-source Python Library that:
1. It was created in 2005,
2. It operates on numerical data types,
3. The core of NumPy are arrays,
4. NumPy arrays are very similar to Python lists (one-dimensional); however, NumPy arrays are multi-dimensional and very faster in math operations on data (50 times faster than lists),
5. The name of NumPy arrays is "ndarray" (n-dimensional arra),
6. The best reliable source for NumPy is: https://numpy.org/

### Installing and Importing NumPy

In [4]:
# let's install first
!pip install numpy

In [5]:
# let's import numpy
import numpy as np  # np is an alias name for numpy 

In [6]:
# let's check the version of the numpy we have 
print(np.__version__)

1.26.4


### Creating NumPy Arrays (narray) from Scratch

##### 1-D Arrays (one dimensional)

In [9]:
# 1. creating an array from a Pthon list 
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
print(a)

[1 2 3 4]


In [11]:
type(a)

numpy.ndarray

In [12]:
# let's create an array using a Python tuple
b = np.array((1,2,3,4))
b

array([1, 2, 3, 4])

In [13]:
type(b)

numpy.ndarray

In [14]:
# an array that contains only zeros
c = np.zeros(7, dtype=float)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [15]:
d  = np.ones(7, dtype=int)
d

array([1, 1, 1, 1, 1, 1, 1])

In [16]:
e = np.full((5,3), 'Degbo')
e

array([['Degbo', 'Degbo', 'Degbo'],
       ['Degbo', 'Degbo', 'Degbo'],
       ['Degbo', 'Degbo', 'Degbo'],
       ['Degbo', 'Degbo', 'Degbo'],
       ['Degbo', 'Degbo', 'Degbo']], dtype='<U5')

In [17]:
e.ndim

2

In [18]:
f = np.arange(0, 12, 2)
f

array([ 0,  2,  4,  6,  8, 10])

In [19]:
g = np.random.randint(9, size=5)
g

array([0, 8, 0, 4, 0])

In [20]:
g.ndim

1

In [21]:
g[-2]

4

In [22]:
g[3]

4

In [23]:
g[:3]

array([0, 8, 0])

In [24]:
# reversing the order of the elements
g[::-1]

array([0, 4, 0, 8, 0])

##### 2-D Arrays 

In [26]:
# let's create a 2-D array
h = np.random.randint(12, size=(4,6))
h

array([[ 3, 11,  5,  2,  4,  3],
       [10,  6,  7,  8,  8,  8],
       [11,  1,  9,  6,  9,  0],
       [11,  7, 10,  6,  9,  4]])

In [27]:
h.ndim

2

In [28]:
h.shape

(4, 6)

In [29]:
# the total number of values in h 
h.size

24

In [30]:
# indexing
h[1,4]

8

In [31]:
# slicing first part is rows , second part is colums
h[0:3, 0:2]

array([[ 3, 11],
       [10,  6],
       [11,  1]])

In [32]:
h[2:8, 4:6]

array([[9, 0],
       [9, 4]])

##### 3-D Arrays

In [34]:
i = np.random.randint(15, size=(4, 4, 5))
i

array([[[ 8, 10,  7,  6,  5],
        [13, 10,  5,  3, 12],
        [14,  1,  3, 14, 11],
        [ 8, 13,  3,  0, 10]],

       [[ 6,  2,  0, 13, 13],
        [ 7,  2,  3,  0, 13],
        [ 8,  4, 14,  7,  6],
        [ 3, 13,  8,  8,  2]],

       [[ 5,  9, 13,  2,  0],
        [ 9, 11,  3,  2,  4],
        [12,  1, 10,  0, 12],
        [11, 11, 13, 11, 12]],

       [[10,  0, 14, 11,  4],
        [ 1, 12, 13,  7,  9],
        [ 6,  3,  1,  9, 11],
        [ 1,  7,  7,  8,  6]]])

In [35]:
i.ndim

3

In [36]:
i.shape

(4, 4, 5)

In [37]:
i.size

80

In [38]:
#indexing
i[2, 3, 2]

13

In [39]:
i[2, 0:2, 1:4]

array([[ 9, 13,  2],
       [11,  3,  2]])

**Observation** Complete before submitting this lab. 
1. How many 3-D array in i? 1
2. How many 2-D array in i? 4
3. How many 1-D array in i? 16
4. How many rows in i? 16
5. How many columns in i? 5
6. What is the shape of i? (4,4,5)
7. What is the dimensionality of it? 3-D
8. How many total values in i? 80 (445)

In [41]:
j = np.random.randint(10, size=(4, 4, 4, 4))
j

array([[[[3, 6, 7, 3],
         [6, 8, 4, 3],
         [0, 1, 2, 7],
         [0, 8, 8, 9]],

        [[6, 0, 5, 4],
         [8, 3, 7, 1],
         [0, 0, 4, 1],
         [9, 2, 5, 5]],

        [[2, 7, 1, 1],
         [8, 4, 1, 4],
         [8, 5, 0, 2],
         [7, 3, 1, 9]],

        [[4, 2, 3, 5],
         [7, 3, 9, 8],
         [3, 4, 4, 1],
         [4, 7, 0, 4]]],


       [[[6, 7, 8, 6],
         [2, 0, 2, 5],
         [0, 2, 9, 7],
         [8, 1, 1, 6]],

        [[7, 5, 9, 0],
         [7, 9, 6, 8],
         [1, 8, 0, 5],
         [2, 9, 7, 2]],

        [[1, 2, 4, 2],
         [8, 1, 3, 3],
         [6, 9, 8, 8],
         [1, 4, 8, 0]],

        [[4, 5, 2, 6],
         [3, 3, 1, 4],
         [5, 0, 1, 4],
         [0, 3, 8, 3]]],


       [[[3, 1, 3, 0],
         [1, 3, 8, 5],
         [4, 3, 8, 9],
         [0, 3, 3, 2]],

        [[0, 0, 0, 9],
         [2, 1, 7, 8],
         [4, 7, 1, 2],
         [4, 6, 9, 5]],

        [[8, 3, 8, 8],
         [6, 8, 4, 3],
         [

### Arrays Concatenation: 

In [43]:
k = np.array([[1,2,3], [4,5,6], [7,8,9]])
k

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
#this is a row
l = np.array([[10,11,12]])
l

array([[10, 11, 12]])

In [45]:
l.shape

(1, 3)

In [46]:
# let's tanspose l
l.T

array([[10],
       [11],
       [12]])

In [47]:
# adding l as a colum 
k_l = np.concatenate((k, l.T), axis=1)
k_l

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [48]:
# adding l as a row
k_l_1 = np.concatenate((k, l), axis=0)
k_l_1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Arrays Splitting

In [50]:
m= np.array([10,20,30,40,50,60])
m

array([10, 20, 30, 40, 50, 60])

In [51]:
# let's split m into 3 arrays
n = np.split(m, 3)
n

[array([10, 20]), array([30, 40]), array([50, 60])]

### Arrays Sorting

In [53]:
o = np.array([9, 7, 3, 5, 1, 8])

In [54]:
o1 = np.sort(o)
o1

array([1, 3, 5, 7, 8, 9])

In [55]:
p = np.array([[4,7,8], [6,2,5], [0,8,1]])
p

array([[4, 7, 8],
       [6, 2, 5],
       [0, 8, 1]])

In [56]:
# let's sort the rows: for sorting rows, we use axis=1
p1 = np.sort(p, axis=1)
p1

array([[4, 7, 8],
       [2, 5, 6],
       [0, 1, 8]])

In [57]:
# let's sort the columns: for sorting columns, we use axis=0
p2 = np.sort(p, axis=0)
p2

array([[0, 2, 1],
       [4, 7, 5],
       [6, 8, 8]])

### Conclusion

- Add
- 15 takeaways that you learned from completing this lab
1. NumPy was created in 2005.
2. NumPy operates on numerical data types. 
3. The core of NumPy are arrays. 
4. NumPy arrays are very similar to Python lists in one-dimensional.
5. NumPy arrays are multi-dimensional.
6. NumPy is 50 times faster in math operations on data than lists. 
7. The name of NumPy arrays is "ndarray".
8. The number of [] would tell you what dimension we have.
9. When indexing we use [].
10. When we slicing it is more than one value we use both ([]).
11. value.shape is to know the shape.
12. Value.size is to get the size.
13. Value.T is to tampose
14. To create an array we use np.array
15. For sorting columns, we use axis=0

##### End of Lab 03.