# Lab 03 - NumPy Library - Florentin Degbo

- NumPy is an open-source Python Library that:
1. It was created in 2005,
2. It operates on numerical data types,
3. The core of NumPy are arrays,
4. NumPy arrays are very similar to Python lists (one-dimensional); however, NumPy arrays are multi-dimensional and very faster in math operations on data (50 times faster than lists),
5. The name of NumPy arrays is "ndarray" (n-dimensional arra),
6. The best reliable source for NumPy is: https://numpy.org/

### Installing and Importing NumPy

In [4]:
# let's install first
!pip install numpy

In [6]:
# let's import numpy
import numpy as np  # np is an alias name for numpy 

In [8]:
# let's check the version of the numpy we have 
print(np.__version__)

1.26.4


### Creating NumPy Arrays (narray) from Scratch

##### 1-D Arrays (one dimensional)

In [11]:
# 1. creating an array from a Pthon list 
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
print(a)

[1 2 3 4]


In [15]:
type(a)

numpy.ndarray

In [17]:
# let's create an array using a Python tuple
b = np.array((1,2,3,4))
b

array([1, 2, 3, 4])

In [19]:
type(b)

numpy.ndarray

In [25]:
# an array that contains only zeros
c = np.zeros(7, dtype=float)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [29]:
d  = np.ones(7, dtype=int)
d

array([1, 1, 1, 1, 1, 1, 1])

In [35]:
e = np.full((5,3), 'Degbo')
e

array([['Degbo', 'Degbo', 'Degbo'],
       ['Degbo', 'Degbo', 'Degbo'],
       ['Degbo', 'Degbo', 'Degbo'],
       ['Degbo', 'Degbo', 'Degbo'],
       ['Degbo', 'Degbo', 'Degbo']], dtype='<U5')

In [45]:
e.ndim

2

In [37]:
f = np.arange(0, 12, 2)
f

array([ 0,  2,  4,  6,  8, 10])

In [41]:
g = np.random.randint(9, size=5)
g

array([2, 7, 7, 5, 5])

In [43]:
g.ndim

1

In [47]:
g[-2]

5

In [49]:
g[3]

5

In [51]:
g[:3]

array([2, 7, 7])

In [53]:
# reversing the order of the elements
g[::-1]

array([5, 5, 7, 7, 2])

##### 2-D Arrays 

In [96]:
# let's create a 2-D array
h = np.random.randint(12, size=(4,6))
h

array([[10,  4,  7,  7,  0,  1],
       [ 5,  2,  1,  9,  0,  9],
       [11,  8,  1,  3,  8,  1],
       [ 5,  0,  1,  1,  0,  0]])

In [60]:
h.ndim

2

In [62]:
h.shape

(4, 6)

In [66]:
# the total number of values in h 
h.size

24

In [76]:
# indexing
h[1,4]

4

In [104]:
# slicing first part is rows , second part is colums
h[0:3, 0:2]

array([[10,  4],
       [ 5,  2],
       [11,  8]])

In [100]:
h[2:8, 4:6]

array([[8, 1],
       [0, 0]])

##### 3-D Arrays

In [108]:
i = np.random.randint(15, size=(4, 4, 5))
i

array([[[10,  5, 14,  4,  4],
        [13,  0,  4,  8, 11],
        [ 5,  1, 11, 14,  2],
        [13,  5,  8,  6,  6]],

       [[ 6,  8,  4, 10, 14],
        [ 7,  3, 13,  1,  5],
        [10, 10,  6,  8,  7],
        [ 9, 10, 14, 13, 14]],

       [[12,  8,  5,  0,  1],
        [ 2, 12,  3,  4, 10],
        [ 3,  4, 13,  5,  3],
        [ 6, 11,  2,  5,  5]],

       [[ 0,  3,  9, 11, 14],
        [14,  4, 12,  5,  8],
        [ 6,  5, 14,  6, 13],
        [ 7,  5,  1, 14, 13]]])

In [110]:
i.ndim

3

In [112]:
i.shape

(4, 4, 5)

In [114]:
i.size

80

In [116]:
#indexing
i[2, 3, 2]

2

In [120]:
i[2, 0:2, 1:4]

array([[ 8,  5,  0],
       [12,  3,  4]])

**Observation** Complete before submitting this lab. 
1. How many 3-D array in i?
2. How many 2-D array in i?
3. How many 1-D array in i?
4. How many rows in i?
5. How many columns in i?
6. What is the shape of i?
7. What is thr dimensionality of it?
8. How many total values in i?

In [125]:
j = np.random.randint(10, size=(4, 4, 4, 4))
j

array([[[[7, 1, 1, 7],
         [6, 6, 8, 1],
         [6, 6, 6, 2],
         [2, 5, 8, 3]],

        [[2, 8, 8, 5],
         [5, 1, 6, 8],
         [9, 1, 3, 5],
         [7, 4, 9, 6]],

        [[4, 0, 9, 4],
         [6, 6, 9, 1],
         [4, 7, 2, 8],
         [7, 5, 6, 9]],

        [[5, 4, 8, 4],
         [7, 2, 5, 3],
         [4, 0, 3, 9],
         [4, 6, 1, 9]]],


       [[[2, 7, 1, 4],
         [9, 6, 4, 2],
         [2, 3, 5, 0],
         [8, 6, 6, 0]],

        [[9, 5, 9, 2],
         [5, 6, 5, 8],
         [1, 1, 0, 3],
         [8, 9, 8, 3]],

        [[3, 5, 0, 2],
         [3, 0, 1, 2],
         [7, 1, 1, 2],
         [6, 9, 8, 5]],

        [[3, 0, 6, 7],
         [6, 4, 6, 6],
         [7, 0, 8, 0],
         [0, 7, 9, 7]]],


       [[[5, 6, 1, 5],
         [8, 8, 4, 0],
         [8, 5, 8, 1],
         [7, 9, 5, 1]],

        [[1, 9, 6, 5],
         [5, 4, 8, 2],
         [8, 6, 4, 8],
         [9, 3, 2, 1]],

        [[4, 1, 7, 3],
         [5, 0, 2, 6],
         [

### Arrays Concatenation: 

In [139]:
k = np.array([[1,2,3], [4,5,6], [7,8,9]])
k

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [157]:
#this is a row
l = np.array([[10,11,12]])
l

array([[10, 11, 12]])

In [145]:
l.shape

(1, 3)

In [147]:
# let's tanspose l
l.T

array([[10],
       [11],
       [12]])

In [159]:
# adding l as a colum 
k_l = np.concatenate((k, l.T), axis=1)
k_l

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [161]:
# adding l as a row
k_l_1 = np.concatenate((k, l), axis=0)
k_l_1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Arrays Splitting

In [168]:
m= np.array([10,20,30,40,50,60])
m

array([10, 20, 30, 40, 50, 60])

In [170]:
# let's split m into 3 arrays
n = np.split(m, 3)
n

[array([10, 20]), array([30, 40]), array([50, 60])]

### Arrays Sorting

In [175]:
o = np.array([9, 7, 3, 5, 1, 8])

In [179]:
o1 = np.sort(o)
o1

array([1, 3, 5, 7, 8, 9])

In [183]:
p = np.array([[4,7,8], [6,2,5], [0,8,1]])
p

array([[4, 7, 8],
       [6, 2, 5],
       [0, 8, 1]])

In [189]:
# let's sort the rows: for sorting rows, we use axis=1
p1 = np.sort(p, axis=1)
p1

array([[4, 7, 8],
       [2, 5, 6],
       [0, 1, 8]])

In [191]:
# let's sort the columns: for sorting columns, we use axis=0
p2 = np.sort(p, axis=0)
p2

array([[0, 2, 1],
       [4, 7, 5],
       [6, 8, 8]])

### Conclusion

- Add
- 15 takeaways that you learned from completing this lab

##### End of Lab 03.