# Lab 04 - Numpy Universal Functions - Florentin Degbo

1. Arrays Aggregations (statistical summaries)
2. Arrays Broadcasting
3. Universal Functions (ufuncs)

### 1. Arrays Aggregations (statistical summaries)

In [4]:
# let's import needed librairies
import numpy as np 
import pandas as pd

In [5]:
a = np.array([3,6,7,9])
a

array([3, 6, 7, 9])

In [6]:
# Let's get the sum of a elements
b = np.sum(a)
b

25

In [7]:
type(np.add)

numpy.ufunc

In [8]:
# let's get the average of a elements
c = np.mean(a)
c

6.25

In [9]:
c_2 = np.average(a)
c_2

6.25

In [10]:
type(np.average)

numpy._ArrayFunctionDispatcher

In [11]:
d = np.max(a)
d

9

In [12]:
e = np.min(a)
e

3

In [13]:
f = np.array([2,4,8,9])

In [14]:
f_1 = np.median(f)
f_1

6.0

In [15]:
g = np.std(a)
g

2.165063509461097

### 2. Arrays Broadcasting
1. Broadcasting perfoms math operation more effectively and faster on **arrays with different shapes**,
2. Broadcasting also uses the "vectorization" concept. 

In [17]:
# 1. Broadcasting on 1-D array using a scaler (number)
h = np.array([4,6,9])
h

array([4, 6, 9])

In [18]:
h1 = h + 5

In [19]:
h1 = h + 5
h1

array([ 9, 11, 14])

In [20]:
h2 = h - 2
h2

array([2, 4, 7])

In [21]:
h3 = h * 3
h3

array([12, 18, 27])

In [22]:
# simple division
h4 = h / 2
h4

array([2. , 3. , 4.5])

In [23]:
# floor division : drops the remaindder 
h5 = h // 2
h4

array([2. , 3. , 4.5])

In [24]:
# 2. Broadcasting on arrays with different shapes 
h6 = np.array([[1], [2], [3]])
h6 

array([[1],
       [2],
       [3]])

In [25]:
h6.shape

(3, 1)

In [26]:
h6.ndim

2

In [27]:
h7 = np.array([4,5,6])
h7

array([4, 5, 6])

In [28]:
h7.shape

(3,)

In [29]:
h7.ndim

1

In [30]:
h8 = h6 + h7
h8

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

### 3. NumPy Universal Functions (ufuncs)
1. Universal functions (ufuncs) are highly effective in performing math operations on arrays by converting iterative objects into vectors,
2. They also use the vectorization concept.

In [32]:
# let's create x and y arrays 
x = np.array([5,8,3,9])
x

array([5, 8, 3, 9])

In [33]:
y = np.array([2,6,7,4])
y

array([2, 6, 7, 4])

In [34]:
# let's check out if a function is a ufunc or not
type(np.sum)

numpy._ArrayFunctionDispatcher

In [35]:
type(np.add)

numpy.ufunc

In [36]:
# 1. ufunc: addition
ufunc1 = np.add(x,y)
ufunc1

array([ 7, 14, 10, 13])

In [37]:
# 2. ufunc: substraction 
ufunc2 = np.subtract(y,x)
ufunc2

array([-3, -2,  4, -5])

In [38]:
# 2. ufunc: substraction 
ufunc2_1 = np.subtract(x,y)
ufunc2_1

array([ 3,  2, -4,  5])

In [39]:
x

array([5, 8, 3, 9])

In [40]:
y

array([2, 6, 7, 4])

In [41]:
# 3. ufunc: multiplication
ufunc3 = np.multiply(y,x)
ufunc3

array([10, 48, 21, 36])

In [42]:
# 4. ufunc: division
ufunc4 = np.divide(x,y)
ufunc4

array([2.5       , 1.33333333, 0.42857143, 2.25      ])

In [43]:
# 4. ufunc: divmod
ufunc4_1 = np.divmod(x,y)
ufunc4_1

(array([2, 1, 0, 2]), array([1, 2, 3, 1]))

In [44]:
# 5. ufunc: power
ufunc5 = np.power(x,y)
ufunc5

array([    25, 262144,   2187,   6561])

In [45]:
# 6. ufunc: remainder
ufunc6 = np.remainder(x,y)
ufunc6

array([1, 2, 3, 1])

In [46]:
# 6. ufunc: mod()
ufunc6_1 = np.mod(x,y)
ufunc6_1

array([1, 2, 3, 1])

In [47]:
# 7. ufunc: absolute()
x1 = np.array([8, -3, 2, -5, -6])
ufunc7 = np.absolute(x1)
ufunc7

array([8, 3, 2, 5, 6])

In [48]:
# 8. ufunc: truncation: removing decimals: trunc()
y1 = np.array([-3.1666, 2.457])
ufunc8 = np.trunc(y1)
ufunc8

array([-3.,  2.])

In [49]:
y1 = np.array([-3.1666, 2.457])
ufunc8 = np.fix(y1)
ufunc8

array([-3.,  2.])

In [50]:
# 9. ufunc: around(): rounding decimals 
ufunc9 = np.around(6.166)
ufunc9

6.0

In [51]:
# 10. ufunc: floor(): rounding decimals to the nearest lower integer
ufunc10 = np.floor([6.166, -2.444])
ufunc10

array([ 6., -3.])

In [52]:
# 11. ufunc: log2(): getting log base 2 
x2 = np.array([5,10,15])
ufunc11 = np.log2(x2)
ufunc11

array([2.32192809, 3.32192809, 3.9068906 ])

In [53]:
# 11. ufunc: log10(): getting log base 10 
x2 = np.array([5,10,15])
ufunc11_1 = np.log10(x2)
ufunc11_1

array([0.69897   , 1.        , 1.17609126])

In [54]:
# 12. ufunc: prod(): getting the product 
x2 = np.array([5,10,15])
ufunc12 = np.prod(x2)
ufunc12

750

In [55]:
# 12. ufunc: prod(): getting the product : 5*10*15*3*7*2
x2 = np.array([5,10,15])
y2 = np.array([3,7,2])

ufunc12_1 = np.prod([x2,y2])
ufunc12_1

31500

In [56]:
# 13. ufunc: lcm(): lowest common multiple
# reduce (): displays a single element
x2 = np.array([5,10,15,18])
ufunc13 = np.lcm.reduce(x2)
ufunc13

90

In [57]:
# 14. ufunc: gcd(): greatest common divisor
# reduce (): displays a single element
x2 = np.array([20,10,32,16])
ufunc14 = np.gcd.reduce(x2)
ufunc14

2

### Conclusion
- Add 15 points that you learned from completing this lab
1. np.sum() provides the sum of all elements in an array.
2. np.mean() provides the mean of an array.
3. np.average() also provides the mean of an array.
4. np.max() identifies the maximum values in an array.
5. np.min() identifies the minimum values in an array.
6. np.median() provides the median value of an array.
7. np.std() calculates the standard deviation of an array.
8. Understanding NumPy Fundamentals is essential for working with large datasets and performing efficient numerical computations.
9. Broadcasting allows arithmetic operations on arrays of different shapes without explicit looping.
10. Vectorization makes calculations faster by simultaneously applying operations to whole arrays instead of going element by element.
11. Universal Functions (ufuncs) are built-in NumPy functions that quickly perform math on arrays.
12. Using ufuncs instead of loops makes your code run faster.
13. For floor division, we use //
14. Broadcasting lets you apply math to arrays of different sizes.
15. The np.absolute() function converts all negative numbers in an array to positive values

#### End of Lab 04.